pipeline {
   agent any
       parameters {
                   text defaultValue: '@Integracion', description: 'TIPO DE PRUEBA FUNCIONAL A EJECUTAR', name: 'TIPO_PRUEBA'
       }



    environment {
        SCM_URL = "https://github.com/JavierCamargoTovio/API_USERS_TEST_SCREMPLAY.git"
        SCM_BRANCH = "main"
        NOMBRE_PROYECTO_GIT = "Test Project Automation Users"
        RECIBE = "javiercamargot22@gmail.com"
    }



    stages {
        stage('Clonar proyecto') {
            steps {
                bat 'git config --global --replace-all http.sslVerify false'
                git url: "${SCM_URL}", branch: "${SCM_BRANCH}"
            }
        }

        stage('Ejecutar pruebas') {
                    steps {
                        script {
                            try{
                               echo "Se ejecuta pruebas: ${TIPO_PRUEBA}"
                               bat "gradlew.bat clean test aggregate --info -DTiporegresion=${TIPO_PRUEBA}";
                               currentBuild.result = 'SUCCESS'
                               }catch(ERRORUNO){
                               echo "Algunos escenarios fallaron"
                               }
                        }
                    }
                }


        stage('Publicar reporte Serenity') {
            steps {
                publishHTML([
                    reportDir: 'target\\site\\serenity',
                    reportFiles: 'index.html',
                    reportName: 'Reporte Serenity',
                    keepAll: true,
                    allowMissing: true,
                    alwaysLinkToLastBuild: true
                ])
            }
        }

        stage('Notificar Resultado') {
            steps {
                script {
                    def fecha = new Date().format("dd/MM/yyyy HH:mm:ss")
                    def mensaje = "Resultado de pruebas (${NOMBRE_PROYECTO_GIT}) - ${fecha}: ${currentBuild.result ?: 'SUCCESS'}"
                    emailext(
                        subject: "Resultado Jenkins - ${currentBuild.result ?: 'SUCCESS'}",
                        body: mensaje,
                        to: "${RECIBE}"
                    )
                }
            }
        }
    }

    post {
        always {
            echo '📌 Pipeline finalizado.'
        }
        success {
            echo '✅ La ejecución fue exitosa.'
        }
        failure {
            echo '❌ La ejecución falló.'
        }
    }
}