import java.text.SimpleDateFormat
import java.util.Date
pipeline {
   agent any
       parameters {
                   text defaultValue: '@Integracion', description: 'TIPO DE PRUEBA FUNCIONAL A EJECUTAR', name: 'TIPO_PRUEBA'
       }



    environment {
        SCM_URL = "https://github.com/JavierCamargoTovio/API_USERS_TEST_SCREMPLAY.git"
        SCM_BRANCH = "main"
        NOMBRE_PROYECTO = "Test Project Automation Users"
        NOMBRE_TRANSACCION = "Test Project Automation Users"
        EMAIL_DEVELOPERS = "javiercamargot22@gmail.com"
    }



    stages {

        stage('Clonar proyecto') {
            steps {
                bat 'git config --global --replace-all http.sslVerify false'
                git url: "${SCM_URL}", branch: "${SCM_BRANCH}"
            }
        }

           stage('Ejecutar pruebas') {
                    steps {
                        script {
                            try{
                               echo "Se ejecuta pruebas: ${TIPO_PRUEBA}"
                               bat "gradlew.bat clean test aggregate --info -DTiporegresion=${TIPO_PRUEBA}";
                               currentBuild.result = 'SUCCESS'
                               }catch(ERRORUNO){
                               echo "Algunos escenarios fallaron"
                               }
                        }
                    }
           }


           stage('Generar evidencia') {
                    steps {
                        script {
                            catchError {
                                   publishHTML([
                                        allowMissing         : false,
                                        alwaysLinkToLastBuild: true,
                                        keepAll              : true,
                                        reportDir            : 'target/site/serenity',
                                        reportFiles          : 'index.html',
                                        reportName           : 'Evidencias Pruebas Aceptacion',
                                        reportTitles         : 'HTML Report Serenity'
                                    ])
                                    echo 'Reporte Html realizado con exito'

                            }
                        }
                    }
           }


           stage('Notificar'){
                   steps{
                     catchError{
                       script{
                         enviarCorreo(currentBuild.result)
                       }
                     }
                   }
           }

   }

 }

def enviarCorreo(resultadoTest) {
    def asunto = ""
    def resultado = ""
    def hero = ""
    def ecosistema = "test user"
    def currentTime = new Date(currentBuild.timeInMillis)
    def formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss")
    def timeInicioPruebas = formato.format(currentTime)
    def urlEvidencia = env.BUILD_URL + "Evidencias_20Pruebas_20Aceptacion/"

    if (currentBuild.result == 'UNSTABLE')
        currentBuild.result = 'FAILURE'

        if (resultadoTest == "SUCCESS") {
            asunto = "${ecosistema} - EJECUCION EXITOSA "
            resultado = "EJECUCION EXITOSA"
            hero = "Todo va bien en la transacci&oacute;n. Para m&aacute;s detalles remitase a los enlaces en la parte inferior de este correo."
        } else {
            asunto = "${ecosistema}  - EJECUCION FALLIDA "
            resultado = "EJECUCION FALLIDA"
            hero = "Se ha encontrado un error en la transacci&oacute;n. Para m&aacute;s detalles remitase a los enlaces en la parte inferior de este correo."
        }

        def body = """<!DOCTYPE html>
                      <html lang="es">

                      <head>
                          <meta charset="UTF-8" />
                          <title></title>
                          <style>
                              body {
                                  display: flex;
                                  justify-content: center;
                                  align-items: center;
                                  height: 100vh;
                                  /* altura de la ventana */
                                  margin: 0;
                                  font-family: Arial, sans-serif;
                                  background-color: #d4d3d3;
                                  justify-content: center;
                                  /* Centra horizontal */
                                  align-items: center;
                              }

                              .contenido {
                                  text-align: center;
                                  background: #edeff0;
                                  padding: 40px;
                                  border-radius: 10px;
                                  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
                              }

                              .transaccion {
                                  color: #100573e9;
                                  font-family: 'Poppins';
                                  letter-spacing: 2px;
                                  font-size: 16px;
                                  word-wrap: break-word;
                              }

                              .job {
                                  color: #191970;
                                  font-family: 'Poppins';
                                  font-size: 18px;
                                  line-height: 34px;
                                  text-align: center;
                                  padding-bottom: 15px;
                                  word-break: break-all;
                              }

                              h1 {
                                  color: #191970;
                                  font-family: 'Poppins';
                              }

                              .text-hero {
                                  color: #008080;
                                  font-family: 'Poppins', Arial, sans-serif;
                                  font-size: 15px;
                                  line-height: 30px;
                                  text-align: center;
                              }

                              .logo {
                                  width: "100%";
                                  color: #fff;
                                  display: flex;
                                  background-color: rgb(246, 246, 245);
                                  justify-content: center;
                                  /* Centra horizontal */
                                  align-items: center;
                                  }


                                  p {
                                      font-family: 'Poppins', Arial, sans-serif;
                                      font-size: 14px;
                                  }


                          </style>
                      </head>

                      <body>
                          <div class="contenido">
                              <p> ${timeInicioPruebas}</p>
                              <h1> ${resultado}</h1>

                              <span class="transaccion">
                                  <h4>TRANSACCION: ${NOMBRE_PROYECTO}<h4>
                              </span>

                              <div class="job">
                                  <h4>Job: '${env.JOB_NAME} [${env.BUILD_NUMBER}]'</h4>
                              </div>

                              <div class="text-hero">
                                  <p> ${hero}</p>
                              </div>

                              <div>
                                  <!-- Jenkins -->
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                          <td style="padding-bottom: 10px;">
                                              <table width="100%" border="0" cellspacing="0" cellpadding="0" dir="rtl"
                                                  style="direction: rtl;">
                                                  <tr>
                                                      <th class="column-dir" dir="ltr" width="245"
                                                          style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;background:#f6efe7;border-radius:0px 10px 10px 0px">
                                                          <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                              <tr>
                                                                  <td class="fluid-img mbr"
                                                                      style="font-size:0pt; line-height:0pt; text-align:center;">
                                                                      <img src="https://i.imgur.com/5zc24YS.png" border="0" alt="" />
                                                                  </td>
                                                              </tr>
                                                          </table>
                                                      </th>
                                                      <th class="column-dir" dir="ltr"
                                                          style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;">
                                                          <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                              <tr>
                                                                  <td class="p30-15 brl"
                                                                      style="padding: 20px; border-radius:10px 0px 0px 10px;"
                                                                      bgcolor="#ffffff" height="100">
                                                                      <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                          <tr>
                                                                              <td class="h3 pb20"
                                                                                  style="color:#445942; font-family:'Poppins', Arial,sans-serif; font-size:14px; line-height:24px; text-align:center; padding-bottom:20px;">
                                                                                  Conozca el estado de la ejecución en Jenkins.
                                                                              </td>
                                                                          </tr>

                                                                          <!-- Button -->
                                                                          <tr>
                                                                              <td align="center">
                                                                                  <table border="0" cellspacing="0" cellpadding="0">
                                                                                      <tr>
                                                                                          <td class="text-button"
                                                                                              style="background:#191970; color:#ffffff; font-family:'Poppins', Arial,sans-serif; font-size:14px; line-height:18px; padding:12px 30px; text-align:center; border-radius:22px;">
                                                                                              <a href="${env.BUILD_URL}" target="_blank"
                                                                                                  class="link-white"
                                                                                                  style="color:#ffffff; text-decoration:none;">
                                                                                                  <span class="link-white"
                                                                                                      style="color:#ffffff; text-decoration:none;">
                                                                                                      <b>Ir a Jenkins</b>
                                                                                                  </span>
                                                                                              </a>
                                                                                          </td>
                                                                                      </tr>
                                                                                  </table>
                                                                              </td>
                                                                          </tr>
                                                                          <!-- END Button -->
                                                                      </table>
                                                                  </td>
                                                              </tr>
                                                          </table>
                                                      </th>
                                                  </tr>
                                              </table>
                                          </td>
                                      </tr>
                                  </table>
                                  <!-- Jenkins -->

                              </div>

                              <div>
                                  <!-- Serenity -->
                                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                      <tr>
                                          <td style="padding-bottom: 10px;">
                                              <table width="100%" border="0" cellspacing="0" cellpadding="0" dir="rtl"
                                                  style="direction: rtl;">
                                                  <tr>
                                                      <th class="column-dir" dir="ltr" width="245"
                                                          style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;background:#f6efe7;border-radius:0px 10px 10px 0px">
                                                          <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                              <tr>
                                                                  <td class="fluid-img mbr"
                                                                      style="font-size:0pt; line-height:0pt; text-align:center;">
                                                                      <img src="https://i.imgur.com/zuIbUrp.png" title="source: imgur.com"
                                                                          border="0" alt="serenity.logo" />
                                                                  </td>
                                                              </tr>
                                                          </table>
                                                      </th>
                                                      <th class="column-dir" dir="ltr"
                                                          style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; direction:ltr;">
                                                          <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                              <tr>
                                                                  <td class="p30-15 brl"
                                                                      style="padding: 20px; border-radius:10px 0px 0px 10px;"
                                                                      bgcolor="#ffffff" height="100">
                                                                      <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                          <tr>
                                                                              <td class="h3 pb20"
                                                                                  style="color:#445942; font-family:'Poppins', Arial,sans-serif; font-size:14px; line-height:24px; text-align:center; padding-bottom:20px;">
                                                                                  Conozca el informe del resultado de la ejecución con Serenity.
                                                                              </td>
                                                                          </tr>
                                                                          <!-- Button -->
                                                                          <tr>
                                                                              <td align="center">
                                                                                  <table border="0" cellspacing="0" cellpadding="0">
                                                                                      <tr>
                                                                                          <td class="text-button"
                                                                                              style="background:#191970; color:#ffffff; font-family:'Poppins', Arial,sans-serif; font-size:14px; line-height:18px; padding:12px 30px; text-align:center; border-radius:22px;">
                                                                                              <a href="${urlEvidencia}" target="_blank"
                                                                                                  class="link-white"
                                                                                                  style="color:#ffffff; text-decoration:none;">
                                                                                                  <span class="link-white"
                                                                                                      style="color:#ffffff; text-decoration:none;">
                                                                                                      <b>Ir al informe</b>
                                                                                                  </span>
                                                                                              </a>
                                                                                          </td>
                                                                                      </tr>
                                                                                  </table>
                                                                              </td>
                                                                          </tr>
                                                                          <!-- END Button -->
                                                                      </table>
                                                                  </td>
                                                              </tr>
                                                          </table>
                                                      </th>
                                                  </tr>
                                              </table>
                                          </td>
                                      </tr>
                                  </table>
                                  <!-- Serenity -->
                              </div>
                      </body>

                      </html>
                                  """

        emailext(
            subject: "${asunto}",
            body: "${body}",
            to: "${EMAIL_DEVELOPERS}",
            mimeType: 'text/html'
        )
}
